language: node_js

node_js:
  - "7"

before_script:
  - cd client && npm install && cd ..
  - cd server && npm install && cd ..

script:
  - cd client && npm test && cd ..
  - cd server && npm test && cd ..